import {useEffect,useRef,useState} from 'react';
import {CheckCircle2,ArrowLeft,ArrowRight,Send} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Label} from '@/components/ui/label';
import {Textarea} from '@/components/ui/textarea';

export default function ActivitySteps({activity,answers,setAnswers,canAnswer,busy,onSubmit,draftStatus}){
 const [step,setStep]=useState(0),[message,setMessage]=useState('');
 const heading=useRef(null),first=useRef(true),questions=activity.perguntas;
 const complete=q=>!!answers[q.id]?.trim()&&(q.tipo!=='alternativa'||q.alternativas.includes(answers[q.id]));
 const completed=questions.filter(complete).length,review=step===questions.length;
 useEffect(()=>{if(first.current){first.current=false;return;}heading.current?.focus({preventScroll:true});heading.current?.scrollIntoView({block:'nearest',behavior:'auto'});},[step]);
 const next=e=>{e.preventDefault();if(!complete(questions[step])){setMessage('Responda esta pergunta para continuar.');return;}setMessage('');setStep(v=>v+1);};
 const submit=e=>{e.preventDefault();if(!review)return;const missing=questions.findIndex(q=>!complete(q));if(missing>=0){setStep(missing);setMessage('Confira a resposta antes de entregar.');return;}onSubmit(e);};
 if(!canAnswer)return <section className="panel space-y-5" aria-label="Respostas da atividade"><h2>Suas respostas</h2>{questions.map((q,i)=><div key={q.id}><h3 className="font-semibold text-sm mb-2">{i+1}. {q.enunciado}</h3><p className="answer-text">{answers[q.id]||'Sem resposta'}</p></div>)}<p className="text-sm text-muted-foreground">{activity.minha_resposta?'Entrega registrada. Acompanhe a correção ou aguarde uma nova tentativa.':'Esta atividade não aceita respostas neste momento.'}</p></section>;
 return <form onSubmit={submit} className="activity-steps" aria-label="Responder atividade"><div className="steps-header"><div><p className="eyebrow">UM PASSO DE CADA VEZ</p><h2 ref={heading} tabIndex={-1}>{review?'Vamos revisar?':`Pergunta ${step+1} de ${questions.length}`}</h2></div><span className="steps-count"><CheckCircle2 size={16}/>{completed}/{questions.length} respondidas</span></div><div className="steps-progress" role="progressbar" aria-label="Perguntas respondidas" aria-valuenow={completed} aria-valuemin={0} aria-valuemax={questions.length}><span style={{width:`${completed/questions.length*100}%`}}/></div><div className="steps-jumps" aria-label="Navegar pelas perguntas">{questions.map((q,i)=><button type="button" key={q.id} disabled={busy} className={`${i===step?'current':''} ${complete(q)?'answered':''}`} aria-label={`Ir para pergunta ${i+1}`} aria-current={i===step?'step':undefined} onClick={()=>{setStep(i);setMessage('');}}>{i+1}</button>)}<button type="button" disabled={busy} className={review?'current':''} aria-current={review?'step':undefined} onClick={()=>{setStep(questions.length);setMessage('');}}>Revisar</button></div>
 <fieldset disabled={busy} className="steps-content">{review?<div className="space-y-5"><p className="text-sm text-muted-foreground">Confira suas respostas. Você pode voltar e ajustar qualquer pergunta antes de enviar.</p>{questions.map((q,i)=><article className="review-answer" key={q.id}><div className="flex justify-between gap-3"><h3>{i+1}. {q.enunciado}</h3><button className="text-primary text-sm shrink-0" type="button" onClick={()=>setStep(i)}>Editar</button></div><p className="answer-text">{answers[q.id]||'Falta responder'}</p></article>)}</div>:<div className="question-stage" key={questions[step].id}><Label htmlFor={`answer-${questions[step].id}`} className="question-prompt">{step+1}. {questions[step].enunciado}</Label>{questions[step].tipo==='alternativa'?<fieldset className="space-y-3" aria-label={questions[step].enunciado}>{questions[step].alternativas.map(option=><label className={`answer-option ${answers[questions[step].id]===option?'selected':''}`} key={option}><input type="radio" name={questions[step].id} value={option} checked={answers[questions[step].id]===option} onChange={()=>setAnswers({...answers,[questions[step].id]:option})}/><span>{option}</span></label>)}</fieldset>:<Textarea id={`answer-${questions[step].id}`} rows={8} maxLength={10000} value={answers[questions[step].id]||''} onChange={e=>setAnswers({...answers,[questions[step].id]:e.target.value})} placeholder="Conte o que você entendeu…"/>}</div>}</fieldset>
 {message&&<p role="alert" className="steps-error">{message}</p>}<div className="steps-footer"><Button type="button" variant="outline" disabled={busy||step===0} onClick={()=>{setStep(v=>v-1);setMessage('');}}><ArrowLeft size={16}/>Anterior</Button>{review?<Button key="deliver" type="submit" disabled={busy||completed!==questions.length}><Send size={16}/>{busy?'Enviando…':activity.minha_resposta?'Enviar nova tentativa':'Enviar respostas'}</Button>:<Button key="advance" type="button" disabled={busy} onClick={next}>{step===questions.length-1?'Revisar respostas':'Próxima'}<ArrowRight size={16}/></Button>}</div><p className="steps-draft" role="status">{draftStatus}</p></form>;
}
