import { Bell, CheckCheck, ArrowUpRight, Inbox } from 'lucide-react';
import '@/notifications.css';
import StatusBadge from '@/components/StatusBadge';
import PushSettings from '@/components/PushSettings';
import PageIntro from '@/components/PageIntro';
import { useEffect, useState } from 'react';
import { Link, useSearchParams, useNavigate } from 'react-router-dom';
import DashboardLayout from '@/components/DashboardLayout';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { TURMAS } from '@/constants/turmas';
import { getUser } from '@/lib/auth';
import api from '@/lib/api';
import { toast } from 'sonner';
import { deadline, activityError } from '@/pages/Activities';
function useLoad(path) {
 const [data,setData]=useState(null),[failed,setFailed]=useState(false);
 useEffect(()=>{let alive=true;setData(null);setFailed(false);api.get(path).then(r=>{if(alive)setData(r.data);}).catch(()=>{if(alive)setFailed(true);});return()=>{alive=false;};},[path]);
 return [data,setData,failed];
}
function Page({title,description,children}) {return <DashboardLayout><PageIntro section={getUser()?.role==='student'?'SEU ESPAÇO / APRENDIZAGEM':'GESTÃO / ACOMPANHAMENTO'} title={title} description={description}/><div className="school-page-content">{children}</div></DashboardLayout>;}
function Loading({failed}) {return <p role={failed?'alert':'status'} className="empty-state">{failed?'Não foi possível carregar. Atualize a página para tentar novamente.':'Carregando…'}</p>;}
export function Workspace() {
 const [data,,failed]=useLoad('/workspace'),student=getUser()?.role==='student';
 return <Page title={student?'Minhas pendências':'Entregas e pendências'} description={student?'Organize as próximas entregas e acompanhe suas correções.':'Veja quem entregou, quem falta entregar e o que precisa de correção.'}>{!data?<Loading failed={failed}/>:<div className="space-y-5"><div className="flex flex-wrap gap-3">{data.correcoes.map(c=><Button variant="outline" asChild key={c.link}><Link to={c.link}>{c.titulo}: {c.quantidade} para corrigir</Link></Button>)}</div>{!data.atividades.length&&<p className="empty-state">Nenhuma atividade disponível.</p>}{[...data.atividades].sort((a,b)=>(a.prazo||'9999').localeCompare(b.prazo||'9999')).map(a=><article key={a.id} className="panel space-y-3"><div className="flex justify-between flex-wrap gap-3"><h2>{a.titulo}</h2><StatusBadge state={student?({'Devolvida':'returned','Corrigida':'graded','Entregue':'review','Prazo encerrado':'closed'}[a.estado]||'pending'):a.corrigir?'correction':'graded'} label={student?undefined:`${a.corrigir} para corrigir`}/></div><p className="text-sm text-muted-foreground">Prazo: {deadline(a.prazo)}</p>{!student&&<div className="grid sm:grid-cols-2 gap-4"><details><summary className="cursor-pointer text-primary">Entregaram ({a.entregaram.length})</summary><ul className="text-sm mt-3 space-y-1">{a.entregaram.map((name,i)=><li key={i}>{name}</li>)}</ul></details><details><summary className="cursor-pointer text-primary">Faltam entregar ({a.faltam.length})</summary><ul className="text-sm mt-3 space-y-1">{a.faltam.map((name,i)=><li key={i}>{name}</li>)}</ul></details></div>}<Button asChild variant="outline"><Link to={a.link}>Abrir atividade</Link></Button></article>)}</div>}</Page>;
}
export function Notifications() {
 const [data,setData,failed]=useLoad('/notifications');
 const [onlyUnread,setOnlyUnread]=useState(false);
 const readAll=async()=>{try{await api.post('/notifications/read-all');setData(list=>list.map(n=>({...n,lida:true})));window.dispatchEvent(new Event('eti-notices'));}catch{toast.error('Não foi possível marcar os avisos.');}};
 const read=async item=>{try{await api.post('/notifications/read',{id:item.id});setData(list=>list.map(x=>x.id===item.id?{...x,lida:true}:x));window.dispatchEvent(new Event('eti-notices'));}catch{toast.error('Não foi possível marcar o aviso como lido.');}};
 const unread=data?.filter(n=>!n.lida).length||0;
 return <Page title="Sua central de avisos" description="Tudo o que merece sua atenção, em um só lugar."><div className="notice-center"><PushSettings/>{!data?<Loading failed={failed}/>:<><div className="notice-toolbar"><div className="notice-tabs"><button aria-pressed={!onlyUnread} onClick={()=>setOnlyUnread(false)}>Todos <span>{data.length}</span></button><button aria-pressed={onlyUnread} onClick={()=>setOnlyUnread(true)}>Não lidos <span>{unread}</span></button></div><Button variant="ghost" disabled={!unread} onClick={readAll}><CheckCheck size={16}/>Marcar todos como lidos</Button></div><div className="notice-list">{data.filter(n=>!onlyUnread||!n.lida).map(n=><article key={n.id} className={`notice-card ${n.lida?'is-read':'is-new'}`}><div className="notice-icon"><Bell size={20}/></div><div className="notice-copy"><div className="notice-meta"><span>{n.lida?'Lido':'Novo aviso'}</span><time>{Number.isNaN(Date.parse(n.data))?'':new Date(n.data).toLocaleDateString('pt-BR',{day:'2-digit',month:'short'})}</time></div><h2>{n.titulo}</h2><div className="notice-actions"><Link to={n.link} onClick={()=>read(n)}>Abrir aviso <ArrowUpRight size={15}/></Link>{!n.lida&&<button onClick={()=>read(n)}><CheckCheck size={15}/>Marcar como lido</button>}</div></div>{!n.lida&&<span className="notice-dot" aria-label="Não lido"/>}</article>)}</div>{!data.some(n=>!onlyUnread||!n.lida)&&<div className="notice-empty"><Inbox size={36}/><h2>Tudo em dia por aqui</h2><p>Os próximos avisos aparecerão neste espaço.</p></div>}</>}</div></Page>;
}
export function Reports() {
 const [turma,setTurma]=useState(''),[data,,failed]=useLoad('/admin/reports'+(turma?'?turma='+encodeURIComponent(turma):''));
 const classes=TURMAS.filter(t=>getUser()?.role==='admin'||getUser()?.turmas?.includes(t.value));
 const download=async()=>{try{const r=await api.get('/admin/reports.csv',{params:turma?{turma}:{},responseType:'blob'});const url=URL.createObjectURL(r.data),a=document.createElement('a');a.href=url;a.download='eti-relatorio.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{toast.error('Não foi possível exportar.');}};
 return <Page title="Relatórios de aprendizagem" description="Acompanhe as entregas, as leituras concluídas e a evolução das notas."><div className="flex flex-wrap gap-4 mb-6"><select aria-label="Filtrar relatório por turma" className="native-select max-w-xs" value={turma} onChange={e=>setTurma(e.target.value)}><option value="">Todas as minhas turmas</option>{classes.map(t=><option key={t.value} value={t.value}>{t.label}</option>)}</select><Button disabled={!data} onClick={download}>Exportar planilha (CSV)</Button></div>{!data?<Loading failed={failed}/>:<><div className="panel overflow-x-auto"><table className="w-full text-sm school-table"><caption className="text-left mb-4">{data.alunos.length} aluno(s) · Média das avaliações recebidas</caption><thead><tr>{['Aluno','Turma','Leituras concluídas','Resumos','Produções','Atividades entregues','Participação','Média'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data.alunos.map(a=><tr key={a.id}><td>{a.nome}</td><td>{a.turma}</td><td>{a.leituras_concluidas}</td><td>{a.resumos}</td><td>{a.producoes}</td><td>{a.atividades_entregues}</td><td>{a.participacao==null?'Sem atividades':a.participacao+'%'}</td><td>{a.media==null?'Sem nota':a.media.toFixed(1)}</td></tr>)}</tbody></table>{!data.alunos.length&&<p className="empty-state">Nenhum aluno nesta turma.</p>}</div><section className="panel mt-5"><h2>Evolução mensal das notas</h2><p className="text-xs text-muted-foreground my-3">Média das avaliações corrigidas em cada mês; não representa uma comparação entre os mesmos trabalhos.</p>{!data.evolucao.length?<p>As médias aparecerão após as primeiras correções.</p>:<ul className="space-y-4">{data.evolucao.map(m=><li key={m.mes}><div className="flex justify-between text-sm mb-2"><span>{m.mes.split('-').reverse().join('/')} · {m.avaliacoes} avaliações</span><strong>{m.media.toFixed(1)}</strong></div><div className="h-2 rounded-full bg-muted"><div className="h-2 rounded-full bg-primary" style={{width:`${m.media*10}%`}}/></div></li>)}</ul>}</section></>}</Page>;
}
export function RecoveryButton({userId}) {
 const [url,setUrl]=useState(''),[busy,setBusy]=useState(false);
 const generate=async()=>{setBusy(true);try{setUrl((await api.post(`/admin/users/${userId}/recovery`)).data.url);}catch{toast.error('Não foi possível gerar o link.');}finally{setBusy(false);}};
 return <div><Button type="button" variant="outline" size="sm" disabled={busy} onClick={generate}>Gerar link de nova senha</Button>{url&&<div className="mt-3 space-y-2"><p className="text-xs text-muted-foreground">Copie e entregue apenas ao titular da conta. Uso único, válido por 30 minutos.</p><Input aria-label="Link para redefinir senha" readOnly value={url} onFocus={e=>e.target.select()}/><Button size="sm" variant="ghost" onClick={()=>setUrl('')}>Ocultar link</Button></div>}</div>;
}
function TeacherCard({teacher,onChange}) {
 const [classes,setClasses]=useState(teacher.turmas||[]),[busy,setBusy]=useState(false);
 const save=async(active)=>{setBusy(true);try{await api.put(`/admin/teachers/${teacher.id}`,{turmas:classes,active});toast.success('Permissões atualizadas.');onChange();}catch(e){toast.error(activityError(e,'Selecione pelo menos uma turma.'));}finally{setBusy(false);}};
 return <article className="panel space-y-4"><div><h2>{teacher.nome}</h2><p className="text-sm text-muted-foreground">{teacher.email} · {teacher.active===false?'Conta desativada':'Conta ativa'}</p></div><ClassChoices value={classes} onChange={setClasses}/><div className="flex flex-wrap gap-3"><Button disabled={busy||!classes.length} onClick={()=>save(teacher.active!==false)}>Salvar turmas</Button><Button variant="outline" disabled={busy||!classes.length} onClick={()=>save(teacher.active===false)}>{teacher.active===false?'Ativar conta':'Desativar conta'}</Button></div><RecoveryButton userId={teacher.id}/></article>;
}
function ClassChoices({value,onChange}) {return <fieldset><legend className="text-sm font-semibold mb-3">Turmas autorizadas</legend><div className="flex flex-wrap gap-3">{TURMAS.map(t=><label className="border rounded-lg p-2 text-sm flex gap-2" key={t.value}><input type="checkbox" checked={value.includes(t.value)} onChange={e=>onChange(e.target.checked?[...value,t.value]:value.filter(x=>x!==t.value))}/>{t.label}</label>)}</div></fieldset>;}
export function Teachers() {
 const [revision,setRevision]=useState(0),[data,,failed]=useLoad('/admin/teachers?revision='+revision),[busy,setBusy]=useState(false);
 const empty={nome:'',email:'',password:'',turmas:[]},[form,setForm]=useState(empty);
 const create=async e=>{e.preventDefault();setBusy(true);try{await api.post('/admin/teachers',form);setForm(empty);setRevision(v=>v+1);toast.success('Conta do professor criada.');}catch(e){toast.error(activityError(e,'Confira os dados e selecione uma turma.'));}finally{setBusy(false);}};
 return <Page title="Contas dos professores" description="Cada professor acessa com sua conta e acompanha apenas as turmas autorizadas."><form className="panel space-y-4 mb-6" onSubmit={create}><h2>Novo professor</h2>{[['nome','Nome','text'],['email','E-mail','email'],['password','Senha inicial (mínimo 10 caracteres)','password']].map(([key,label,type])=><div key={key}><Label htmlFor={'teacher-'+key}>{label}</Label><Input id={'teacher-'+key} type={type} required minLength={key==='password'?10:2} maxLength={key==='password'?72:160} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></div>)}<ClassChoices value={form.turmas} onChange={turmas=>setForm({...form,turmas})}/><Button disabled={busy||!form.turmas.length} type="submit">Criar conta do professor</Button></form>{!data?<Loading failed={failed}/>:<div className="space-y-5">{data.map(t=><TeacherCard key={t.id+JSON.stringify(t)} teacher={t} onChange={()=>setRevision(v=>v+1)}/>)}{!data.length&&<p className="empty-state">Cadastre o primeiro professor.</p>}</div>}</Page>;
}
export function PasswordRecovery() {
 const [params]=useSearchParams(),token=params.get('token'),navigate=useNavigate();
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const submit=async e=>{e.preventDefault();setBusy(true);try{const r=await api.post(token?'/auth/reset-password':'/auth/forgot-password',token?{token,password}:{email});setMessage(r.data.message);if(token){toast.success('Senha atualizada.');navigate('/login');}}catch(e){setMessage(activityError(e,'Não foi possível concluir. Tente novamente.'));}finally{setBusy(false);}};
 return <main className="min-h-screen bg-background flex items-center justify-center p-5"><form onSubmit={submit} className="panel w-full max-w-md space-y-5"><p className="eyebrow">ETI LEITURA</p><h1 className="text-2xl">{token?'Escolha uma nova senha':'Recuperar acesso'}</h1><p className="text-sm text-muted-foreground">{token?'O link pode ser utilizado uma única vez.':'Informe seu e-mail. Se o envio de e-mails ainda não estiver configurado, solicite um link ao administrador da escola.'}</p><div><Label htmlFor="recovery-value">{token?'Nova senha (mínimo 10 caracteres)':'E-mail'}</Label><Input id="recovery-value" type={token?'password':'email'} minLength={token?10:undefined} maxLength={token?72:254} required value={token?password:email} onChange={e=>token?setPassword(e.target.value):setEmail(e.target.value)}/></div><Button type="submit" disabled={busy}>{busy?'Aguarde…':token?'Salvar nova senha':'Solicitar recuperação'}</Button>{message&&<p role="status" className="text-sm">{message}</p>}<Link className="block text-sm text-primary" to="/login">Voltar para entrar</Link></form></main>;
}
