// Visual and interaction checks with explicit fixtures; no database is modified.
const fs=require('fs'),path=require('path'),http=require('http');
const {chromium}=require('../frontend/node_modules/playwright');
process.chdir(path.resolve(__dirname,'..'));
const root=path.resolve(__dirname,'../frontend/build');
const server=http.createServer((req,res)=>{let file=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(root+path.sep)&&file!==root){res.writeHead(403);return res.end();}if(!fs.existsSync(file)||fs.statSync(file).isDirectory())file=path.join(root,'index.html');const ext=path.extname(file);res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml'})[ext]||'application/octet-stream');fs.createReadStream(file).pipe(res);});
(async()=>{await new Promise(r=>server.listen(4173,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1050}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
const user={id:'test',nome:'Mariana Silva',email:'mariana@example.com',turma:'7º ANO',role:'student'};
const books=[{id:'1',titulo:'O Pequeno Príncipe',autor:'Antoine de Saint-Exupéry',progress:45,nivel_ensino:'AMBOS'},{id:'2',titulo:'A Ilha do Tesouro',autor:'Robert Louis Stevenson',progress:15,nivel_ensino:'FUNDAMENTAL'},{id:'3',titulo:'Dom Casmurro',autor:'Machado de Assis',progress:100,nivel_ensino:'MÉDIO'},{id:'4',titulo:'O Jardim Secreto',autor:'Frances Hodgson Burnett',progress:0,nivel_ensino:'AMBOS'}].map((b,i)=>({...b,descricao:'Uma história para descobrir novas perspectivas e compartilhar ideias.',capa_url:`data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="300" height="400"><rect width="300" height="400" fill="${['#233f62','#467369','#a16b4d','#6a668c'][i]}"/><rect x="20" y="20" width="260" height="360" rx="2" fill="none" stroke="#ffffff55"/><circle cx="150" cy="165" r="65" fill="none" stroke="#ffffff44" stroke-width="2"/><path d="M85 210 L150 90 L215 210Z" fill="none" stroke="#ffffff77"/><text x="150" y="295" text-anchor="middle" font-size="17" font-family="serif" fill="white">${b.titulo}</text><text x="150" y="340" text-anchor="middle" font-size="10" font-family="sans-serif" fill="#ffffffaa">ETI LEITURA · ACERVO DE TESTE</text></svg>`)}`}));
await page.route('**/api/**',async route=>{const url=new URL(route.request().url()),p=url.pathname;let data=[];if(p==='/api/stats')data={total_books:4,my_summaries:2};else if(p==='/api/admin/stats')data={total_books:4,total_users:28,total_summaries:12,total_productions:7};else if(p==='/api/books')data=books;else if(p==='/api/auth/me')data=user;else if(p==='/api/calendar')data=[{id:'e1',titulo:'Roda de leitura',data:`${url.searchParams.get('ano')}-${String(url.searchParams.get('mes')).padStart(2,'0')}-22`,cor:'#294b9c'}];else if(p==='/api/books/1')data=books[0];else if(p==='/api/books/1/progress')data={percentage:45};else if(p==='/api/books/1/summary')return route.fulfill({status:404,json:{detail:'Sem resumo'}});return route.fulfill({json:data});});
await page.goto('http://127.0.0.1:4173/login');await page.getByRole('heading',{name:'Bom ter você por aqui.'}).waitFor();await page.waitForTimeout(900);await page.screenshot({path:'docs/login-desktop.png',fullPage:true});await page.getByTestId('toggle-auth-mode').click();await page.getByTestId('input-nome').waitFor();await page.getByTestId('input-nome').fill('Aluno de teste');for(const option of await page.locator('#turma option').all()){const value=await option.getAttribute('value');if(value){await page.getByTestId('input-turma').selectOption(value);if(await page.getByTestId('input-nome').inputValue()!=='Aluno de teste')throw Error('Registration lost form state after class selection');await page.getByTestId('submit-button').waitFor();}}await page.getByTestId('toggle-auth-mode').click();
await page.evaluate(u=>{localStorage.setItem('user',JSON.stringify(u));localStorage.setItem('token','visual-test-only')},user);
await page.goto('http://127.0.0.1:4173/dashboard');await page.getByText('Leituras concluídas',{exact:true}).waitFor();await page.waitForTimeout(900);await page.screenshot({path:'docs/painel-desktop.png',fullPage:true});
await page.goto('http://127.0.0.1:4173/library');await page.getByRole('button',{name:'Concluídos',exact:true}).click();if(await page.locator('.book-card').count()!==1)throw Error('Completed filter failed');await page.getByRole('button',{name:'Todos',exact:true}).click();await page.getByRole('textbox',{name:'Buscar por título ou autor'}).fill('principe');if(await page.locator('.book-card').count()!==1)throw Error('Accent insensitive search failed');await page.getByRole('textbox',{name:'Buscar por título ou autor'}).fill('');await page.waitForTimeout(900);await page.screenshot({path:'docs/biblioteca-desktop.png',fullPage:true});
for(const url of ['/summaries','/text-productions','/profile','/book/1','/editor/1']){await page.goto('http://127.0.0.1:4173'+url);await page.locator('main').waitFor();await page.waitForTimeout(250);}
await page.goto('http://127.0.0.1:4173/admin/users');await page.waitForURL('**/dashboard');
await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Abrir menu'}).click();await page.getByRole('navigation',{name:'Navegação principal',exact:true}).getByRole('link',{name:'Biblioteca',exact:true}).click();await page.getByRole('heading',{name:'Biblioteca',exact:true}).waitFor();if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');await page.waitForTimeout(900);await page.screenshot({path:'docs/biblioteca-mobile.png',fullPage:true});
await page.evaluate(u=>localStorage.setItem('user',JSON.stringify({...u,role:'admin'})),user);await page.setViewportSize({width:1440,height:1050});for(const url of ['/admin/users','/admin/books','/admin/add-book','/admin/summaries','/admin/text-productions','/admin/mural','/admin/calendar']){await page.goto('http://127.0.0.1:4173'+url);await page.locator('main').waitFor();await page.waitForTimeout(250);}
await page.goto('http://127.0.0.1:4173/dashboard');await page.getByRole('heading',{name:'Painel do professor',exact:true}).waitFor();await page.waitForTimeout(900);await page.screenshot({path:'docs/admin-desktop.png',fullPage:true});
await page.getByRole('button',{name:'Ativar tema escuro'}).click();await page.reload();await page.getByRole('button',{name:'Ativar tema claro'}).waitFor();if(!await page.locator('html').evaluate(e=>e.classList.contains('dark')))throw Error('Theme persistence failed');await page.screenshot({path:'docs/painel-novo-escuro.png',fullPage:true});await page.getByRole('button',{name:'Ativar tema claro'}).click();
if(await page.getByText('Acompanhe cada conquista',{exact:true}).count())throw Error('Removed panel is still present');
if(await page.getByText('Calendário escolar',{exact:true}).count())throw Error('Calendar is still in professor panel');
await page.getByRole('button',{name:'Todas as áreas',exact:true}).click();
if(await page.getByRole('navigation',{name:'Navegação principal',exact:true}).getByRole('link',{name:'Avisos',exact:true}).count())throw Error('Notifications duplicated in menu');
await page.getByRole('button',{name:'Fechar menu',exact:true}).last().click();
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(300);if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Teacher mobile overflow');await page.screenshot({path:'docs/painel-novo-mobile.png',fullPage:true});
if(errors.length)throw Error(errors.join('\n'));console.log('PASS: login/registration, student/admin pages, search, progress filters, admin route guard, mobile navigation, no horizontal overflow, no runtime errors. API fixtures only.');await browser.close();server.close();})().catch(e=>{console.error(e);server.close();process.exit(1)});

